[project]
name = "ezconfig"
version = "0.1.0"
description = "Seamless Pydantic-based YAML configs"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pydantic",
    "pydantic-settings",
    "rich",
]
